# Generated by Django 5.1.1 on 2024-10-04 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('volume', models.IntegerField(blank=True, default=0, null=True)),
                ('sets', models.IntegerField(blank=True, default=0, null=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
