# Generated by Django 5.1.1 on 2024-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_set_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
