# Generated by Django 5.1.1 on 2024-10-09 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_exercisehistory_options_exercisehistoryset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroupTag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary',
            field=models.ManyToManyField(blank=True, related_name='primary_muscles', to='workouts.musclegrouptag'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_muscles', to='workouts.musclegrouptag'),
        ),
    ]
